apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  backstage.io/kubernetes-id: sample-app-argocd

resources:
#  - project.yaml
#  - rolebindings.yaml
  - sample-app-argocd-deploy.yaml
  - sample-app-argocd-service.yaml
  - sample-app-argocd-route.yaml
